name             'symfony2-chef'
maintainer       'Robert Dolca'
maintainer_email 'robert.dolca@gmail.com'
license          'All rights reserved'
description      'Symfony2 app deployment'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt'
depends 'application'
depends 'application_php'
depends 'symfony2'
depends 'htop'
depends 'mysql'
depends 'curl'
depends 'java'
depends 'npm'
depends 'nodejs'
depends 'mysql'
depends 'git'
depends 'php'
depends 'composer'
